### ISSUE TITLE
Can't see any network log in release mode

### ISSUE THREAD

**Issue by Soliman13** [odemolliens/react-native-netwatch#54]
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.12.1",
    "@react-native-community/datetimepicker": "3.4.3",
    "@react-native-community/image-editor": "^2.3.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.2.4",
    "@react-native-firebase/analytics": "^11.2.0",
    "@react-native-firebase/app": "^11.2.0",
    "@react-native-firebase/crashlytics": "^11.2.0",
    "@react-native-firebase/perf": "^11.2.0",
    "@react-native-picker/picker": "^1.15.0",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "axios": "^0.21.1",
    "buffer": "^6.0.3",
    "date-fns": "^2.21.1",
    "deepmerge": "^4.2.2",
    "expo-blur": "^9.0.3",
    "expo-local-authentication": "^11.0.2",
    "expo-notifications": "^0.11.5",
    "formik": "^2.2.6",
    "geolib": "^3.3.1",
    "html-entities": "2.3.2",
    "i18next": "^20.2.1",
    "instabug-reactnative": "^10.0.0",
    "jail-monkey": "^2.3.3",
    "jetifier": "^1.6.6",
    "latinize": "^0.5.0",
    "notificare-push-lib-react-native": "^2.5.3",
    "querystring": "0.2.1",
    "react": "16.13.1",
    "react-i18next": "^11.8.13",
    "react-native": "0.63.4",
    "react-native-circular-progress": "^1.3.7",
    "react-native-config": "^1.4.2",
    "react-native-device-info": "^8.1.0",
    "react-native-fs": "^2.17.0",
    "react-native-geocoding": "^0.4.0",
    "react-native-geolocation-service": "^5.2.0",
    "react-native-gesture-handler": "^1.10.1",
    "react-native-highlight-words": "^1.0.1",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-picker": "^2.3.1",
    "react-native-image-size": "^1.1.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-localize": "^2.0.2",
    "react-native-logging-tools": "^1.3.0",
    "react-native-maps": "0.27.1",
    "react-native-modal": "^11.10.0",
    "react-native-netwatch": "^1.2.4",
    "react-native-paper": "^4.8.1",
    "react-native-pdf": "6.3.0",
    "react-native-permissions": "^3.0.0",
    "react-native-picker-select": "^8.0.4",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.1",
    "react-native-sensitive-info": "^6.0.0-alpha.9",
    "react-native-share": "5.2.2",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.1-0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swiper": "^1.6.0",
    "react-native-unimodules": "^0.13.3",
    "react-native-user-inactivity": "^1.2.0",
    "react-native-vector-icons": "^8.1.0",
    "react-native-webview": "^11.4.0",
    "react-navigation-backhandler": "^2.0.1",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-persist-sensitive-storage": "git+https://github.com/Squirel-SI/redux-persist-sensitive-storage.git",
    "redux-saga": "^1.1.3",
    "reselect": "^4.0.0",
    "rn-fetch-blob": "^0.12.0",
    "tealium-react-native": "^2.0.2",
    "yup": "0.32.9"
  },

# Issue (iOS & Android)

When running the app on debug mode, I can see logs of redux actions & network calls as expected, when running the app in release mode, there are only redux actions that are logged, I can't see any network call.

**Debug mode logs**
:white_check_mark: Redux actions
:white_check_mark: Network calls

**Release mode logs**
:white_check_mark: Redux actions
:x: Network calls

**Comment by imranMnts** [comment]
You are using `Instabug-React-Native` which uses the same process as Netwatch, (`XHRInterceptor`)  and we are not allowed to use it together.

https://github.com/Instabug/Instabug-React-Native/blob/master/utils/XhrNetworkInterceptor.js

**Comment by imranMnts** [comment]
Issue fixed in v1.2.7
