### ISSUE TITLE
No Log coming for network requests

### ISSUE THREAD

**Issue by kush11** [odemolliens/react-native-netwatch#89]
Added for network logs but on shake its coming as empty 
Added for redux and it logs all the redux actions with their payload 

Check this screen shot for the Netwatch added to root of page  
<img width="456" alt="Screenshot 2021-09-11 at 11 13 19 AM" src="https://user-images.githubusercontent.com/14028043/132937695-4588578a-0eb5-42fc-94e6-0ede388b3f37.png">

For API call in my project, I am using Axios

**Comment by GuillaumeHemmen** [comment]
Seems to be related to https://github.com/odemolliens/react-native-netwatch/issues/54

**Comment by imranMnts** [comment]
@kush11 Can you add your package.json to know what do you have in your dependencies that can cause this

**Comment by kush11** [comment]
> @kush11 Can you add your package.json to know what do you have in your dependencies that can cause this

@imranMnts 

"dependencies": {
    "@kesha-antonov/react-native-action-cable": "^1.1.0",
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/cli": "^4.10.1",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/netinfo": "^6.0.2",
    "@react-native-community/push-notification-ios": "^1.4.1",
    "@react-native-firebase/analytics": "^11.4.1",
    "@react-native-firebase/app": "^11.4.1",
    "@react-native-firebase/crashlytics": "^11.4.1",
    "@react-native-firebase/perf": "^11.4.1",
    "@react-native-firebase/remote-config": "^11.4.1",
    "@sentry/react-native": "^1.9.0",
    "@supersami/rn-foreground-service": "^1.1.1",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "accordion-collapse-react-native": "^1.0.1",
    "axios": "^0.21.1",
    "chalk": "^4.1.0",
    "clevertap-react-native": "^0.5.0",
    "color": "^3.1.2",
    "debounce": "^1.2.0",
    "global": "^4.4.0",
    "i18n-js": "^3.8.0",
    "jetifier": "^1.6.5",
    "lottie-react-native": "^4.0.2",
    "moment": "^2.24.0",
    "native-base": "^2.13.14",
    "react": "17.0.1",
    "react-content-loader": "^5.1.3",
    "react-native": "0.64.1",
    "react-native-appsflyer": "^5.4.1",
    "react-native-calendar-picker": "^7.1.1",
    "react-native-check-app-install": "^0.0.5",
    "react-native-code-push": "^6.3.0",
    "react-native-config": "^1.3.3",
    "react-native-contacts": "^6.0.3",
    "react-native-deep-linking": "^2.2.0",
    "react-native-device-info": "^6.0.2",
    "react-native-dropdown-picker": "^5.1.23",
    "react-native-exception-handler": "^2.10.8",
    "react-native-fs": "^2.18.0",
    "react-native-geocoding": "^0.5.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-image-picker": "^2.3.3",
    "react-native-loading-spinner-overlay": "^2.0.0",
    "react-native-localize": "^2.0.1",
    "react-native-location": "^2.5.0",
    "react-native-looped-carousel": "^0.1.13",
    "react-native-maps": "^0.27.1",
    "react-native-mixpanel": "^1.2.4",
    "react-native-modal": "^11.5.6",
    "react-native-month-year-picker": "^1.6.3",
    "react-native-navigation": "^7.13.0",
    "react-native-navigation-hooks": "^6.3.0",
    "react-native-netwatch": "^1.2.6",
    "react-native-offline": "^5.7.0",
    "react-native-otp-verify": "^1.0.3",
    "react-native-pager-view": "^5.2.1",
    "react-native-paper": "^4.9.2",
    "react-native-progress": "^4.1.2",
    "react-native-progress-circle": "^2.1.0",
    "react-native-push-notification": "^7.2.3",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-settings": "^0.2.3",
    "react-native-share": "^3.7.0",
    "react-native-svg": "^12.1.0",
    "react-native-swipe-list-view": "^3.2.5",
    "react-native-tab-view": "^3.0.1",
    "react-native-truecaller-sdk": "^1.0.5",
    "react-native-vector-icons": "^8.1.0",
    "react-native-walkthrough-tooltip": "^1.1.11",
    "react-native-webp-format": "^1.1.2",
    "react-native-webview": "^11.0.0",
    "react-native-youtube": "^2.0.1",
    "react-native-youtube-iframe": "^1.4.0",
    "react-redux": "^7.2.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.1.3",
    "rn-fetch-blob": "^0.12.0",
    "url-search-params-polyfill": "^8.1.0",
    "uuid-random": "^1.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/runtime": "^7.5.0",
    "@react-native-community/eslint-config": "^0.0.3",
    "@types/jest": "^26.0.10",
    "@types/react": "^16.9.48",
    "@types/react-native": "^0.63.10",
    "@typescript-eslint/eslint-plugin": "^3.10.1",
    "@typescript-eslint/parser": "^3.10.1",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.1.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "cz-conventional-changelog": "3.3.0",
    "danger": "^7.0.2",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.7.0",
    "eslint": "7.2.0",
    "eslint-config-airbnb": "18.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-jest": "^23.20.0",
    "eslint-plugin-jsx-a11y": "^6.3.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.6",
    "eslint-plugin-react-hooks": "4.0.0",
    "eslint-plugin-react-native": "^3.9.1",
    "husky": "^4.2.5",
    "jest": "^26.4.2",
    "jsdom": "13.0.0",
    "jsdom-global": "3.0.2",
    "metro-react-native-babel-preset": "^0.51.1",
    "prettier": "^1.16.1",
    "pretty-quick": "^3.0.0",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.6.3",
    "react-native-typescript-transformer": "^1.2.13",
    "react-test-renderer": "16.8.1",
    "sinon": "^9.0.3",
    "ts-jest": "26.0.0",
    "typescript": "^4.0.2"
  },

**Comment by imranMnts** [comment]
Issue fixed in v1.2.7
